### ISSUE TITLE
I have some questions to ask

### ISSUE THREAD

**Issue by K-l6408** [r3trodev/earthbound-backgrounds-shaders-godot#1]
Hi, I just wanted to ask a few questions:
First of all, how did you manage to do the effects seen in the two examples on the left? Did you use multiple shaders or just one?
Second, can I use this shader in a game of mine? (not for commercial purposes)

**Comment by r3trodev** [comment]
Every background shown on the page has a demo that is a separate scene in Godot. You can download the whole repository and open the project in Godot 3.x. You can then take a look at the working demos of the shader in the src/battle/backgrounds folder.

You can use the shader and even this project however you see fit, it is released under the CC0 license, so it means I am no more the copyright owner and you can even make modifications to the code and redistribute those modifications yourself.

**Comment by K-l6408** [comment]
Thank you so much for your reply, I didn't expect it so early! I guess I can close the issue then?
